name = "MattParkerJigsawPuzzleProblem"
uuid = "0b6cfa58-065e-4a28-bd8c-ef93a167ff61"
authors = ["MarkNahabedian <naha@mit.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
XML = "72c71f33-b9b6-44de-8c94-c961784809e2"

[compat]
DataStructures = "0.18"
Literate = "2.19"
XML = "0.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
